import bcrypt from 'bcryptjs';

export async function seedDatabase(db) {
  const passwordHash = await bcrypt.hash('SecurePassword!123', 10);

  // 1. Users
  db.tables.users = [
    {
      id: 'USR-PAT-7741',
      email: 'sarah.connor@example.com',
      password_hash: passwordHash,
      name: 'Sarah Connor',
      phone: '+1 (555) 018-9921',
      role: 'PATIENT',
      tenant_id: 'tenant_central_04',
      dob: '1988-04-12',
      delivery_address: '742 Evergreen Terr, Springfield',
      fido2_verified: false,
      hipaa_consented: true,
      created_at: new Date('2026-09-01T08:00:00Z'),
    },
    {
      id: 'USR-PHARM-8821',
      email: 'kimberly.young@wellspringmeds.com',
      password_hash: passwordHash,
      name: 'Dr. Kimberly Young, PharmD',
      phone: '+1 (555) 244-8800',
      role: 'PHARMACIST',
      tenant_id: 'tenant_east_04',
      pharmacy_name: 'WellSpring Meds',
      license_number: 'RPH-99281-IL',
      fido2_verified: true,
      hipaa_consented: true,
      created_at: new Date('2026-09-01T08:00:00Z'),
    },
    {
      id: 'USR-PHARM-8822',
      email: 'robert.vance@apexmedicos.com',
      password_hash: passwordHash,
      name: 'Dr. Robert Vance, PharmD',
      phone: '+1 (555) 321-4455',
      role: 'PHARMACIST',
      tenant_id: 'tenant_central_04',
      pharmacy_name: 'Apex Medicos',
      license_number: 'RPH-77102-IL',
      fido2_verified: true,
      hipaa_consented: true,
      created_at: new Date('2026-09-01T08:00:00Z'),
    },
    {
      id: 'USR-TRUST-9041',
      email: 'elena.vance@trustops.internal',
      password_hash: passwordHash,
      name: 'Elena Vance',
      phone: '+1 (555) 998-1122',
      role: 'TRUST_OFFICER',
      tenant_id: 'public_core',
      fido2_verified: true,
      hipaa_consented: true,
      created_at: new Date('2026-09-01T08:00:00Z'),
    },
  ];

  // 2. Pharmacies
  db.tables.pharmacies = [
    {
      id: 'PHARM-01',
      tenant_id: 'tenant_east_04',
      name: 'WellSpring Meds',
      license_number: 'DL-88492-MED',
      dea_number: 'BW9928104',
      npi_number: '1942004819',
      pic_name: 'Dr. Kimberly Young, PharmD',
      trust_score: 98,
      distance_miles: 0.8,
      delivery_eta: 'Same-Day Ready',
      cold_chain_certified: true,
      rating: 4.8,
      address: '104 Healthcare Blvd, Springfield',
    },
    {
      id: 'PHARM-02',
      tenant_id: 'tenant_central_04',
      name: 'Apex Medicos',
      license_number: 'DL-88492-MED',
      dea_number: 'BA4419208',
      npi_number: '1882049102',
      pic_name: 'Dr. Robert Vance, PharmD',
      trust_score: 94,
      distance_miles: 1.4,
      delivery_eta: '35 mins',
      cold_chain_certified: false,
      rating: 4.9,
      address: '220 Center Way, Springfield',
    },
    {
      id: 'PHARM-03',
      tenant_id: 'tenant_central_04',
      name: 'CareFirst Express',
      license_number: 'DL-55210-MED',
      dea_number: 'BC1102938',
      npi_number: '1029384756',
      pic_name: 'Dr. Marcus Albers, PharmD',
      trust_score: 91,
      distance_miles: 2.1,
      delivery_eta: 'Delivers in 2 hrs',
      cold_chain_certified: false,
      rating: 4.7,
      address: '55 Express Rd, Springfield',
    },
  ];

  // 3. Medicines
  db.tables.medicines = [
    {
      id: 'MED-01',
      generic_name: 'Cetirizine HCl',
      brand_name_equivalent: 'Zyrtec®',
      dosage_form: 'Film-Coated Tablet',
      strength: '10mg',
      category: 'Allergy & Cold',
      generic_price: 8.99,
      brand_price: 18.50,
      savings_percentage: 51,
      unit_price_string: '$0.30 / tablet',
      fda_bioequivalent_rating: 'AB-Rated',
      otc_regulated: true,
      image_url: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=400',
      indications: 'Temporarily relieves symptoms of hay fever or upper respiratory allergies: runny nose, sneezing, itchy/watery eyes.',
      dosage_adult: 'One 10mg tablet once daily; do not exceed one 10mg tablet in 24 hours.',
      dosage_senior: 'Consult physician or start at 5mg daily.',
      active_ingredient: 'Cetirizine HCl USP 10mg (Antihistamine)',
      inactive_ingredients: 'Colloidal silicon dioxide, croscarmellose sodium, hypromellose, lactose monohydrate, magnesium stearate.',
      shelf_stability_months: 24,
    },
    {
      id: 'MED-02',
      generic_name: 'Paracetamol',
      brand_name_equivalent: 'Tylenol® / Calpol',
      dosage_form: 'Oral Caplet',
      strength: '500mg',
      category: 'Pain & Fever',
      generic_price: 3.20,
      brand_price: 5.50,
      savings_percentage: 42,
      unit_price_string: '$0.16 / tablet',
      fda_bioequivalent_rating: 'AB-Rated',
      otc_regulated: true,
      image_url: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=400',
      indications: 'Relief of mild to moderate pain including headache, toothache, muscle aches, and fever reduction.',
      dosage_adult: '500mg to 1000mg every 4 to 6 hours as needed. Maximum 4000mg in 24 hours.',
      dosage_senior: '500mg every 6 hours. Maximum 3000mg in 24 hours recommended.',
      active_ingredient: 'Acetaminophen / Paracetamol 500mg (Analgesic/Antipyretic)',
      inactive_ingredients: 'Corn starch, povidone, pregelatinized starch, sodium starch glycolate, stearic acid.',
      shelf_stability_months: 36,
    },
    {
      id: 'MED-03',
      generic_name: 'Amoxicillin Trihydrate',
      brand_name_equivalent: 'Amoxil®',
      dosage_form: 'Oral Capsule',
      strength: '500mg',
      category: 'Antibiotics (Rx)',
      generic_price: 14.80,
      brand_price: 28.00,
      savings_percentage: 47,
      unit_price_string: '$0.74 / capsule',
      fda_bioequivalent_rating: 'AB-Rated',
      otc_regulated: false,
      image_url: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=400',
      indications: 'Treatment of bacterial infections including ear, nose, throat, lower respiratory tract, and skin.',
      dosage_adult: '500mg every 8 hours or 875mg every 12 hours for 7 to 10 days.',
      dosage_senior: 'Dosage adjustment recommended if severe renal impairment.',
      active_ingredient: 'Amoxicillin Trihydrate equivalent to 500mg Amoxicillin',
      inactive_ingredients: 'Magnesium stearate, sodium lauryl sulfate, gelatin, titanium dioxide.',
      shelf_stability_months: 24,
    },
  ];

  // 4. Pharmacy Inventory
  db.tables.pharmacy_inventory = [
    {
      id: 'INV-01',
      tenant_id: 'tenant_east_04',
      pharmacy_id: 'PHARM-01',
      medicine_id: 'MED-01',
      batch_number: '#CT-4421',
      mfg_date: '10/2024',
      exp_date: '10/2026',
      shelf_stability_months: 24,
      current_count: 142,
      unit_price: 8.99,
      velocity: 'High (28/day)',
      location_bin: 'Shelf A-14',
      status: 'Adequate',
      assay_verified: true,
    },
    {
      id: 'INV-02',
      tenant_id: 'tenant_central_04',
      pharmacy_id: 'PHARM-02',
      medicine_id: 'MED-01',
      batch_number: '#CT-4429',
      mfg_date: '11/2024',
      exp_date: '11/2026',
      shelf_stability_months: 24,
      current_count: 85,
      unit_price: 9.20,
      velocity: 'Moderate (12/day)',
      location_bin: 'Shelf B-02',
      status: 'Adequate',
      assay_verified: true,
    },
    {
      id: 'INV-03',
      tenant_id: 'tenant_central_04',
      pharmacy_id: 'PHARM-02',
      medicine_id: 'MED-02',
      batch_number: '#PA-1092',
      mfg_date: '04/2024',
      exp_date: '04/2027',
      shelf_stability_months: 36,
      current_count: 310,
      unit_price: 3.20,
      velocity: 'Very High (64/day)',
      location_bin: 'Bay C-08',
      status: 'Optimal',
      assay_verified: true,
    },
    {
      id: 'INV-04',
      tenant_id: 'tenant_central_04',
      pharmacy_id: 'PHARM-02',
      medicine_id: 'MED-03',
      batch_number: '#AM-9904',
      mfg_date: '08/2024',
      exp_date: '08/2026',
      shelf_stability_months: 24,
      current_count: 24,
      unit_price: 14.80,
      velocity: 'Moderate (14/day)',
      location_bin: 'Vault S-02',
      status: 'Reorder Soon',
      assay_verified: true,
    },
    {
      id: 'INV-05',
      tenant_id: 'tenant_central_04',
      pharmacy_id: 'PHARM-02',
      medicine_id: 'MED-01',
      batch_number: '#DX-8819',
      mfg_date: '01/2024',
      exp_date: '10/2024',
      shelf_stability_months: 1,
      current_count: 18,
      unit_price: 5.84, // 35% discount applied
      velocity: 'Slow',
      location_bin: 'Quarantine Rack Q-1',
      status: 'Quarantine',
      assay_verified: true,
    },
  ];

  // 5. Couriers
  db.tables.couriers = [
    {
      id: 'DVR-882',
      name: 'Marcus Jenkins',
      badge_number: '#MC-882',
      phone: '+1 (555) 019-2831',
      vehicle_type: 'Bio-Carrier eBike',
      is_verified: true,
      cold_chain_certified: true,
      current_lat: 39.7817,
      current_lng: -89.6501,
      avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    },
    {
      id: 'DVR-412',
      name: 'David Alvarez',
      badge_number: '#MC-412',
      phone: '+1 (555) 019-7712',
      vehicle_type: 'Express Van',
      is_verified: true,
      cold_chain_certified: true,
      current_lat: 39.7845,
      current_lng: -89.655,
      avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    },
  ];

  // 6. Orders
  db.tables.orders = [
    {
      id: 'GM-94281',
      tenant_id: 'tenant_east_04',
      patient_id: 'USR-PAT-7741',
      pharmacy_id: 'PHARM-01',
      courier_id: 'DVR-882',
      status: 'EN_ROUTE',
      total_amount: 14.49,
      medical_release_pin_hash: await bcrypt.hash('4892', 8),
      raw_pin: '4892',
      tamper_seal_number: '#SEAL-9082',
      destination_address: '742 Evergreen Terr, Springfield',
      eta_minutes: 18,
      distance_miles: 1.2,
      current_temp_f: 68.4,
      pin_attempts: 0,
      created_at: new Date('2026-09-08T10:14:00Z'),
      updated_at: new Date('2026-09-08T10:38:00Z'),
    },
  ];

  // 7. Order Items
  db.tables.order_items = [
    {
      id: 'OI-01',
      order_id: 'GM-94281',
      medicine_id: 'MED-01',
      quantity: 1,
      unit_price: 8.99,
      lot_number: 'CT-4421',
      exp_date: '09/2026',
    },
    {
      id: 'OI-02',
      order_id: 'GM-94281',
      medicine_id: 'MED-02',
      quantity: 1,
      unit_price: 5.50,
      lot_number: 'PA-1092',
      exp_date: '04/2027',
    },
  ];

  // 8. Audit Events (Seeded with real SHA-256 Merkle blocks)
  db.tables.audit_events = [
    {
      id: 'AE-01',
      event_id: 'EVT-889104',
      timestamp: new Date('2026-09-08T14:02:44.029Z'),
      actor_id: 'USR-TRUST-9041',
      actor_name: 'Elena Vance',
      actor_role: 'LEAD_TRUST_OFFICER',
      actor_email: 'elena.vance@genricmed.internal',
      action: 'SELLER_STATUS_CHANGE',
      target: 'Apex Healthcare (tenant_central_04)',
      classification: 'HIGH PRIORITY',
      tenant_context: 'tenant_central_04',
      payload_json: {
        action: 'SELLER_APPROVAL',
        compliance_tags: ['FR-ADM-01', 'HIPAA-164.312', 'SOC2-CC6.1'],
        justification: 'Cold-chain audit passed TX-H772',
      },
      previous_hash: '0000000000000000000000000000000000000000000000000000000000000000',
      merkle_root: '0x99a3...b12',
      signature_hash: '0x99a3f761c4b281d77a092ef51b9201f84821ca39e557bb01d48c89b12',
    },
    {
      id: 'AE-02',
      event_id: 'EVT-889103',
      timestamp: new Date('2026-09-08T13:58:12.840Z'),
      actor_id: 'SYS-CRON-01',
      actor_name: 'SYSTEM_CRON',
      actor_role: 'EXPIRY_DAEMON',
      actor_email: 'cron.daemon@genricmed.internal',
      action: 'CATALOG_BATCH_QUARANTINE',
      target: 'Cetirizine HCl #CT-4421 (tenant_east)',
      classification: 'WARNING',
      tenant_context: 'tenant_east_04',
      payload_json: {
        action: 'BATCH_QUARANTINE_TRIGGER',
        entity_affected: 'LOT-CT-4421',
        reason: 'Proactive 60-day threshold audit trigger',
      },
      previous_hash: '0x99a3f761c4b281d77a092ef51b9201f84821ca39e557bb01d48c89b12',
      merkle_root: '0x77c2...89a',
      signature_hash: '0x77c2a1290bb394efca010b91e772ab48102d91f2884a7e9120198ca1',
    },
    {
      id: 'AE-03',
      event_id: 'EVT-889102',
      timestamp: new Date('2026-09-08T13:45:00.112Z'),
      actor_id: 'USR-PHARM-8821',
      actor_name: 'Dr. Kimberly Young',
      actor_role: 'PHARMD_SUPERVISOR',
      actor_email: 'k.young@wellspringmeds.internal',
      action: 'PRESCRIPTION_PHI_ACCESS',
      target: 'Order #ORD-94281 (RX-99210)',
      classification: 'HIPAA / PHI',
      tenant_context: 'tenant_east_04',
      payload_json: {
        action: 'PHI_ACCESS',
        entity_affected: 'ORD-94281',
        encryption: 'AES-256-GCM',
      },
      previous_hash: '0x77c2a1290bb394efca010b91e772ab48102d91f2884a7e9120198ca1',
      merkle_root: '0x44d9...65c',
      signature_hash: '0x44d98a09bbef1209384bcda8891028374a9190ab1289cf09128374ae',
    },
  ];

  // 9. Prescriptions
  db.tables.prescriptions = [
    {
      id: 'RX-99210',
      tenant_id: 'tenant_east_04',
      patient_id: 'USR-PAT-7741',
      pharmacy_id: 'PHARM-01',
      rx_number: 'RX-ILL-2026-99210',
      doctor_name: 'Dr. Gregory House, MD',
      doctor_npi: '1092837465',
      medicine_id: 'MED-01',
      dosage_instructions: 'Take 1 tablet (10mg) by mouth once daily in the morning for seasonal allergic rhinitis.',
      refills_remaining: 3,
      status: 'ACTIVE',
      image_url: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=400',
      extracted_text: 'Rx: Cetirizine HCl 10mg PO Daily. Refills: 3. Signed Dr. G. House',
      ddi_warnings: [],
      created_at: new Date('2026-09-02T10:00:00Z'),
    },
    {
      id: 'RX-99211',
      tenant_id: 'tenant_central_04',
      patient_id: 'USR-PAT-7741',
      pharmacy_id: 'PHARM-02',
      rx_number: 'RX-ILL-2026-99211',
      doctor_name: 'Dr. Allison Cameron, MD',
      doctor_npi: '1928374650',
      medicine_id: 'MED-03',
      dosage_instructions: 'Take 1 capsule (500mg) every 8 hours for 10 days with full glass of water.',
      refills_remaining: 0,
      status: 'ACTIVE',
      image_url: null,
      extracted_text: 'Rx: Amoxicillin Trihydrate 500mg TID x 10d. Refills: 0. Signed Dr. A. Cameron',
      ddi_warnings: [],
      created_at: new Date('2026-09-04T11:30:00Z'),
    },
  ];

  // 10. Chain of Custody Events
  db.tables.chain_of_custody_events = [
    {
      id: 'COC-01',
      tenant_id: 'tenant_east_04',
      order_id: 'GM-94281',
      event_type: 'ORDER_PACKAGED',
      timestamp: new Date('2026-09-08T10:20:00Z'),
      actor_id: 'USR-PHARM-8821',
      actor_name: 'Dr. Kimberly Young, PharmD',
      actor_role: 'PHARMACIST',
      location_lat: 39.7817,
      location_lng: -89.6501,
      ambient_temp_f: 68.0,
      tamper_seal_status: 'INTACT',
      notes: '5-point regulatory verification checklist approved. Tamper seal #SEAL-9082 applied.',
    },
    {
      id: 'COC-02',
      tenant_id: 'tenant_east_04',
      order_id: 'GM-94281',
      event_type: 'COURIER_HANDOVER',
      timestamp: new Date('2026-09-08T10:25:00Z'),
      actor_id: 'DVR-882',
      actor_name: 'Marcus Jenkins',
      actor_role: 'COURIER',
      location_lat: 39.7817,
      location_lng: -89.6501,
      ambient_temp_f: 68.2,
      tamper_seal_status: 'INTACT',
      notes: 'Courier custody accepted. Placed in active temperature-controlled carrier.',
    },
    {
      id: 'COC-03',
      tenant_id: 'tenant_east_04',
      order_id: 'GM-94281',
      event_type: 'TRANSIT_TELEMETRY_PING',
      timestamp: new Date('2026-09-08T10:35:00Z'),
      actor_id: 'DVR-882',
      actor_name: 'Marcus Jenkins',
      actor_role: 'COURIER',
      location_lat: 39.7830,
      location_lng: -89.6520,
      ambient_temp_f: 68.4,
      tamper_seal_status: 'INTACT',
      notes: 'En route to destination address.',
    },
  ];
}

