export const ORDER_STATUS = {
  PLACED: 'PLACED',
  DISPENSED: 'DISPENSED',
  DISPATCHED: 'DISPATCHED',
  EN_ROUTE: 'EN_ROUTE',
  DELIVERED: 'DELIVERED',
  PIN_EXCEPTION: 'PIN_EXCEPTION',
  CANCELLED: 'CANCELLED',
};

export const INVENTORY_STATUS = {
  ADEQUATE: 'Adequate',
  OPTIMAL: 'Optimal',
  REORDER_SOON: 'Reorder Soon',
  QUARANTINE: 'Quarantine',
};

export const AUDIT_CLASSIFICATION = {
  HIGH_PRIORITY: 'HIGH PRIORITY',
  WARNING: 'WARNING',
  HIPAA_PHI: 'HIPAA / PHI',
  CRITICAL_BLOCKED: 'CRITICAL / BLOCKED',
  MEDIUM_AUDIT: 'MEDIUM AUDIT',
};
